stages:
- name: "test"
- name: "release"
  if: branch = tt
- name: "production"
  if: branch = master

dist: xenial
language: node_js
node_js:
- 12
cache: npm
before_install:
- export PATH=~/npm/node_modules/.bin:$PATH
- sudo apt-get install -y sshpass
- cd $TRAVIS_BUILD_DIR/server
- >
  awk
  -v FS==
  -v REMOTE_DOCKER_IP="$REMOTE_DOCKER_IP"
  -v REMOTE_DOCKER_PORT="$REMOTE_DOCKER_PORT"
  '/^REMOTE_DOCKER_IP/{sub($2, REMOTE_DOCKER_IP, $2); print > "test.env"} 
  /^REMOTE_DOCKER_PORT/{sub($2, REMOTE_DOCKER_PORT, $2); print > "test.env"}' 
  OFS==
  template.env;
  cat test.env
install:
- cd $TRAVIS_BUILD_DIR/server
- npm install
- cd $TRAVIS_BUILD_DIR/client
- npm install

jobs:
  include:
  - stage: test 
    name: "server lint sequence"
    before_script:
    - cd $TRAVIS_BUILD_DIR/server
    script:
    - npm start test.unit

  - script:
    - npm start test.unit
    name: "server test sequence"
    before_script:
    - cd $TRAVIS_BUILD_DIR/server

  - script:
    - npm start lint
    name: "client lint sequence"
    before_script:
    - cd $TRAVIS_BUILD_DIR/client

  - script:
    - npm start test
    name: "client test sequence"
    before_script:
    - cd $TRAVIS_BUILD_DIR/client

  - stage: release 
    name: "deploy server to release server"
    script:
    - >
      sshpass -p "$PROD_USER_PASSWORD"
      scp -P $PROD_SERVER_PORT -r -o StrictHostKeyChecking=no 
      ./ $PROD_USER_ID@$PROD_SERVER_HOST:/home/boost/server -v
    - >
      sshpass -p "$PROD_USER_PASSWORD"
      ssh -p $PROD_SERVER_PORT -o StrictHostKeyChecking=no 
      $PROD_USER_ID@$PROD_SERVER_HOST "cd server && npm start production"
    before_script:
    - cd $TRAVIS_BUILD_DIR/server

  - script:
    - >
      sshpass -p $PROD_USER_PASSWORD
      scp -P $PROD_SERVER_PORT -r -o StrictHostKeyChecking=no 
      ./dist $PROD_USER_ID@$PROD_SERVER_HOST:/home/boost/client
    - >
      sshpass -p $PROD_USER_PASSWORD
      ssh -p $PROD_SERVER_PORT -o StrictHostKeyChecking=no 
      $PROD_USER_ID@$PROD_SERVER_HOST "cd client && npm start"
    name: "deploy client to release server"
    before_script:
    - cd $TRAVIS_BUILD_DIR/client
    - npm start build

  - stage: production
    name: "deploy server to production server"
    script:
    - >
      sshpass -p "$PROD_USER_PASSWORD"
      scp -P $PROD_SERVER_PORT -r -o StrictHostKeyChecking=no 
      ./ $PROD_USER_ID@$PROD_SERVER_HOST:/home/boost/server
    - >
      sshpass -p "$PROD_USER_PASSWORD"
      ssh -p $PROD_SERVER_PORT -o StrictHostKeyChecking=no 
      $PROD_USER_ID@$PROD_SERVER_HOST "cd server && npm start production"
    before_script:
    - cd $TRAVIS_BUILD_DIR/server

  - script:
    - >
      sshpass -p $PROD_USER_PASSWORD
      scp -P $PROD_SERVER_PORT -r -o StrictHostKeyChecking=no 
      ./dist $PROD_USER_ID@$PROD_SERVER_HOST:/home/boost/client
    - >
      sshpass -p $PROD_USER_PASSWORD
      ssh -p $PROD_SERVER_PORT -o StrictHostKeyChecking=no 
      $PROD_USER_ID@$PROD_SERVER_HOST "cd client && npm start"
    name: "deploy client to production server"
    before_script:
    - cd $TRAVIS_BUILD_DIR/client
    - npm start build
